# Exploratory data analysis

# Frequency and percentage analysis

freq_purchase_channel = final_data['Purchase_Channel'].value_counts()
freq_purchase_channel


perc_purchase_channel = freq_purchase_channel/len(final_data['Purchase_Channel'])*100
perc_purchase_channel



# Value counts method The final data for analysis has been loaded for you within the variable final_data. 
# Your task is to analyse the data to find the percentage of employees left your company. 
# Write necessary code for the following tasks: Perform frequency analysis on the variable churned and 
# keep the output within the variable freq_churned Calculate the percentage of churned using the output within 
# the variable freq_churned and keep the result of percentage within the variable perc_churned Finally, 
# call the variable perc_churned

import pandas as pd
final_data = pd.read_csv("practice_data.csv", header=0)

# Frequency analysis of the churned column
freq_churned = final_data['churned'].value_counts()
# Calculate percentage of churned
perc_churned = (freq_churned / freq_churned.sum()) * 100
# Display the percentage of churned
perc_churned


# Descriptive statistics and analysis

final_data = final_data[final_data['Average_Purchase_Amount'] != 13423411.958]

round(final_data.describe())


# Descriptive statistics
# The final data for analysis has been loaded for you within the variable final_data. 
# Your task is to analyse the data to find the descriptive measures of all the numeric variables.
# Write necessary code for performing descriptive analysis on the final_data


# Group by data analysis method 

city_purchase_amount = final_data.groupby('City')['Average_Purchase_Amount'].median()
city_purchase_amount

# Group by method The final data for analysis has been loaded for you within the variable final_data. 
# Your task is to analyse the data to find the average sales revenue generated by the existing employees and employees 
# who left the job. Write necessary code to perform following tasks: Apply groupby analysis where you will group 
# the Sales Revenue Generated variable by the variable churned to find the average value. Keep the output within 
# the variable SRG_churned. Finally, call the variable SRG_churned.\

import pandas as pd
final_data = pd.read_csv("practice_data.csv", header=0)

# Group by churned and calculate average Sales Revenue Generated
SRG_churned = final_data.groupby('churned')['Sales Revenue Generated'].mean()
# Display the result
SRG_churned


# Pivot table analysis 

pivot_table = final_data.pivot_table(index = 'Churn_Status', 
                                     values = ['Recency', 'Frequency_Score', 'Monetary_Score'], 
                                     aggfunc = {'Recency':'mean', 'Frequency_Score':'mean', 'Monetary_Score':'mean', 'Churn_Status':'count'})


pivot_table = pivot_table.rename(columns = {'Churn_Status':'Freq_churn', 
                                            'Recency':'Mean_recency', 
                                            'Frequency_Score':'Mean_FS', 'Monetary_Score':'Mean_MS'})

pivot_table



# Pivot table
# The final data for analysis has been loaded for you within the variable final_data. 
# Your task is to analyse the data to find the average Task Completion Rate, 
# Interpersonal Skills Rating between churned and not-churned employees and the counts of churned employees.
# Write necessary code to perform following tasks:
# Create a pivot table to calculate average Task Completion Rate, Interpersonal Skills Rating by the variable churned.
# Add the counts of unique churned variable's values.
# Keep the output within the variable pivot_table.Finally, call the variable pivot_table.

import pandas as pd
final_data = pd.read_csv("practice_data.csv", header=0)

# Create a pivot table with averages and counts by churned
pivot_table = pd.pivot_table(
    final_data,
    index='churned',
    values=['Task Completion Rate', 'Interpersonal Skills Rating'],
    aggfunc=['mean', 'count']
)

# Display the pivot table
pivot_table


# Cross-tabulation analysis

cross_tab = pd.crosstab(final_data['City'], final_data['Purchase_Channel'])
cross_tab


# Cross-tabulation
# The final data for analysis has been loaded for you within the variable final_data. 
# Your task is to analyse the data to create a cross-tabulation between employees work accuracy and 
# whether they got churned. Write necessary code to perform following tasks:
# Create a cross table to calculate the number of employees got churned by the levels of employees' Accuracy of Work
# Place the variable churned first, and Accuracy of Work secondly within the crosstab method.
# Keep the output within the variable cross_tab. Finally, call the variable cross_tab. 

import pandas as pd
final_data = pd.read_csv("practice_data.csv", header=0)

# Create cross-tabulation between churned and Accuracy of Work
cross_tab = pd.crosstab(
    final_data['churned'],
    final_data['Accuracy of Work']
)
# Display the cross-tabulation
cross_tab



# Correlation analysis for numeric data

num_variables = final_data.select_dtypes(include = ['number']).columns

num_variables

round(final_data[num_variables].corr(), 3)


# Correlation analysis
# The final data for analysis has been loaded for you within the variable final_data.Your task is to analyse the data 
# to find the relationship among three significant factors of the given employee data.
# Write necessary code to perform following tasks: Create a correlation matrix using the variables Task Completion Rate, 
# Decision-Making Skills Rating and Sales Revenue Generated. Round the values within the output to be 3 decimal points. 

