# Class Notes : 

import matplotlib.pyplot as plt
import seaborn as sns


# Bar chart from value counts output
plt.figure(figsize=(8, 6))
freq_churned.plot(kind='bar')
plt.title('Frequencies of churned employees')
plt.xlabel('Churned')
plt.ylabel('Count')
plt.show()



plt.figure(figsize=(8, 6))
sns.countplot(x='churned', data=final_data)
plt.title('Frequencies of churned employees')
plt.xlabel('Churned')
plt.ylabel('Count')
plt.show()



plt.figure(figsize=(8, 6))
cross_tab.plot(kind='bar', stacked=False)
plt.title('Working accuracy level by churned employees')
plt.xlabel('Churned')
plt.ylabel('Count')
plt.show()



plt.figure(figsize=(8, 6))
sns.countplot(x='churned', hue='Accuracy of Work', data=final_data)
plt.title('Working accuracy level by churned employees')
plt.xlabel('Churned')
plt.ylabel('Count')
plt.show()




plt.figure(figsize=(8, 6))
perc_churned.plot(kind='pie', autopct='%1.2f%%')
plt.title('Percentage of churned employees')
plt.ylabel('')
plt.show()



### Seaborn has no code for pie chart by default

plt.figure(figsize=(8, 6))
SRG_dept.plot(kind='line', marker='o')
plt.title('Average sales revenue generated by Employees')
plt.xlabel('Churned')
plt.ylabel('Mean sales revenue')
plt.show()



plt.figure(figsize=(8, 6))
sns.lineplot(x='department', y='Sales Revenue Generated', data=final_data, marker='o')
plt.title('Average sales revenue generated by Employees')
plt.xlabel('Department')
plt.ylabel('Average sales revenue')
plt.show()



plt.figure(figsize=(8, 6))
final_data['Task Completion Rates'].plot(kind='hist', bins=5)
plt.title('Histogram of Task Completion Rates')
plt.xlabel('Task Completion Rates|')
plt.ylabel('Frequency')
plt.show()



plt.figure(figsize=(8, 6))
sns.histplot(final_data['Task Completion Rates'], bins = 5)
plt.title('Histogram of Task Completion Rates')
plt.xlabel('Task Completion Rates')
plt.ylabel('Frequency')
plt.show()



plt.figure(figsize=(8, 6))
plt.scatter(final_data['Interpersonal Skills Rating'], final_data['Decision-Making Skills Rating'])
plt.title('Scatterplot of Interpersonal Skills Rating vs Decision-Making Skills Rating')
plt.xlabel('Interpersonal Skills Rating')
plt.ylabel('Decision-Making Skills Rating')
plt.show()



plt.figure(figsize=(8, 6))
sns.regplot(x='Interpersonal Skills Rating', y='Decision-Making Skills Rating', data=final_data)
plt.title('Interpersonal Skills Rating vs Decision-Making Skills Rating with Trend Line')
plt.xlabel('Interpersonal Skills Rating')
plt.ylabel('Decision-Making Skills Rating')
plt.show()




# matplotlib does not have heatmap




plt.figure(figsize=(8, 6))
sns.heatmap(corr, annot=True)
plt.title('Heatmap of Correlation Matrix')
plt.show()




# matplotlib does not have boxplot




plt.figure(figsize=(8, 6))
sns.boxplot(x='Task Completion Rates', y = 'churned', data = final_data)
plt.title('Boxplot of Task Completion Rates')
plt.xlabel('Task Completion Rates')
plt.show()